### PR TITLE
[WIP] Support mtl-2.3

### PR DESCRIPTION
**Pull request by sjakobi**
Upstream issues:

* [x] https://github.com/haskell/parsec/issues/148
* [x] https://github.com/monadfix/microlens/issues/151

### CODE REVIEW

**Comment by andreasabel** [comment]
This is certainly a safe change, but let's see how the `ExceptT` story plays out:
- https://github.com/haskell/mtl/issues/117

**Comment by sjakobi** [comment]
This patch isn't needed anymore, since the `ExceptT` changes were reverted in `mtl-2.3.1`.

**Comment by phadej** [comment]
You need to exclude `mtl-2.3` from the build-depends range though.,

**Comment by andreasabel** [comment]
> You need to exclude `mtl-2.3` from the build-depends range though.,

Did that in:
- https://github.com/hackage-trustees/hackage-cli/pull/51

**Pull request closed without merging**
